### ISSUE TITLE
Flow Job Delay Not Working

### ISSUE THREAD

**Issue by ccravens** [taskforcesh/bullmq#1036]
I am not able to delay a job submitted to a flow. I have a flow where I'm adding about 7 parents to execute one after another. One of those workers I need to delay but about 30 secs. I'm doing that with the following:

```yaml
      {
        name: 'JOB_NAME',
        queueName: 'QUEUE_NAME',
       {},
        prefix: '',
       {
           delay: 30000
       },
        children: [],
      };
```

I am able to get a delay with Jobs that are not part of a flow. And I am creating a QueueScheduler for the Queues that I would like to delay with the following:

```typescript
new QueueScheduler('QUEUE_NAME', {connection: ...})
```

According to this discussion, seems like it could be a missing feature: https://github.com/taskforcesh/bullmq/discussions/998
