### ISSUE TITLE
[Bug]: BullMq tries to create a new IORedis connect  after receiving a connection in parameter 

### ISSUE THREAD

**Issue by ikemHood** [taskforcesh/bullmq#2497]
### Version

v5.4.6

### Platform

NodeJS

### What happened?

BullMq tries to create a new IORedis connection to 127.0.0.1:6379 and fails with an ECONNREFUSED.
the econnrefused is expected as there's no redis instance in my localhost. 

the problem is that even tho a connection was passed, it tries to create a new instance which fails

### How to reproduce.

Next Js 14
Docker node:20-alpine

worker and queue helper file
````js
//worker.helpers.js
import { Queue, Worker } from 'bullmq';
import Redis from 'ioredis';
import { functionName } from './Function.js';

const REDIS_URI = process.env.REDIS_URI;

const connection = new Redis({
  url: REDIS_URI,
  maxRetriesPerRequest: null
});

console.log(REDIS_URI) // logs expected redis cloud url

// Create a queue instance
const queue = new Queue('a-queue', { connection });

// Create a worker instance
const worker = new Worker(
  'a-queue',
  async (job) => {
    console.log(`Processing job ${job.id}`);
    const { params } = job.data;
    try {
        return await functionName(params)
    } catch (error) {
      console.error('Error doing something: ', error);
      throw new Error(error)
    }
  },
  {
    concurrency: 1,
    connection
  },
);

// Handle worker events
worker.on('completed', (job, result) => {
  console.log(`Job ${job.id} completed with result: ${result}`);
});

worker.on('failed', (job, err) => {
  console.log(`Job ${job.id} failed with error: ${err.message}`);
});

console.log("Worker Running: ", worker.isRunning())
export { queue };

````

.env file
````env
#.env
 REDIS_URL=redis://redis:6379
MONGODB_URI=mongodb://mongo:27017/data
````

docker compose file

````yaml

#docker-composer.yaml

version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/mongo

  redis:
    image: redis
    restart: always
    ports:
      - '6370:6370'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:

````

Dockerfile

````Dockerfile
#Dockerfile

# Use the official Node.js 18 image as the base
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Build the Next.js app
RUN npm run build

# Expose the port for the Next.js app
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "start"]
````

run

````bash
docker compose up 
````

### Relevant log output

```shell
app-1    | Error: connect ECONNREFUSED 127.0.0.1:6379
app-1    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
app-1    |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
app-1    |   errno: -111,
app-1    |   code: 'ECONNREFUSED',
app-1    |   syscall: 'connect',
app-1    |   address: '127.0.0.1',
app-1    |   port: 6379
app-1    | }
app-1    | Error: connect ECONNREFUSED 127.0.0.1:6379
app-1    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
app-1    |     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
app-1    |   errno: -111,
app-1    |   code: 'ECONNREFUSED',
app-1    |   syscall: 'connect',
app-1    |   address: '127.0.0.1',
app-1    |   port: 6379
app-1    | }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
