### ISSUE TITLE
[Bug]: Error: connect ECONNREFUSED 127.0.0.1:6379 even though no localhost configured anywhere

### ISSUE THREAD

**Issue by urtuba** [taskforcesh/bullmq#2793]
### Version

v5.13.0

### Platform

NodeJS

### What happened?

Hey, I use redis with docker compose. It is installed by original image. I got connrefused like this:

```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

My redis connection. It parses uri & uses seperate conn. config. It parse uri correctly according to logs below & tested properly: (yes, worker options excluding connection did not utilized, not related)
```
import Redis from 'ioredis'

import ENV from './environment'
import logger from './logger'

const parseRedisUri = (uri) => {
  const [protocol, rest] = uri.split('://')

  if (!rest) {
    throw new Error('Invalid URI')
  }

  // Check if there's a username and password in the URI
  const [authPart, hostPortAndDb] = rest.includes('@') ? rest.split('@') : [undefined, rest]
  const [username, password] = authPart ? authPart.split(':') : [undefined, undefined]

  // Split host, port, and database (the part after /)
  const [hostPort, db] = hostPortAndDb.split('/')
  const [host, port] = hostPort.includes(':') ? hostPort.split(':') : [hostPort, undefined]

  return {
    host, // Host from the URI (e.g., 'redis')
    port, // Port from the URI (e.g., '6379')
    username, // Username from the URI, or undefined if missing
    password, // Password from the URI, or undefined if missing
    db: db // Database from the URI (e.g., '0'), or undefined if missing
  }
}

const createRedis = () => {
  // naxretriesperrequest: 3,

  const redisOptions = parseRedisUri(ENV.REDIS_URI)

  logger.info(redisOptions)

  return new Redis({
    ...redisOptions,
    maxRetriesPerRequest: null
  })
}

const redis = createRedis()

// on error print redis options
redis.on('error', (error) => {
  logger.error(`Error connecting to Redis: ${error.message} Redis options: ${JSON.stringify(redis.options)}`)
})

redis.on('connect', () => {
  logger.info('Connected to Redis')
})

export default redis
```

ENV in code does not contain any localhost:
```
/app # printenv | grep REDIS_URI
REDIS_URI=redis://redis:6379/0
```

Also I can see first successfull connection message!
```
{"level":30,"time":1727641030469,"pid":18,"hostname":"1e30ac1f6e87","app":"data-crawler","env":"production","host":"redis","port":"6379","db":"0"}
{"level":30,"time":1727641030809,"pid":18,"hostname":"1e30ac1f6e87","app":"xx","env":"production","msg":"Connected to Redis"}
```

Only bullmq uses redis in my app. Redis imported by only bullmq.js. Bullmq imported by only this file and used this functions to get queue and worker always without overwriting connection option:

```
import { Queue, Worker } from 'bullmq'

import redis from './redis'
import logger from './logger'

export const createQueue = (queueName, options) => {
  logger.info(`Creating queue: ${queueName}`)

  const queue = new Queue(queueName, {
    createClient: (type) => {
      switch (type) {
        case 'client':
          return redis
        case 'subscriber':
          return redis
        case 'bclient':
          return redis.duplicate()
        default:
          throw new Error('Unexpected connection type: ', type)
      }
    },
    ...options
  })

  queue.on('completed', async (job) => {
    logger.info(`Job ${job.id} completed`)
  })

  queue.on('failed', async (job, err) => {
    logger.error(`Job ${job.id} failed: ${err.message}`)
  })

  queue.on('cleaned', (jobs, type) => {
    logger.info(`Cleaned ${jobs.length} ${type} jobs`)
  })

  return queue
}

export const createWorker = (queueName, workerFunction, options) => {
  logger.info(`Creating worker for queue: ${queueName}`)

  return new Worker(queueName, workerFunction, {
    connection: redis
  })
}

```

I can connect my redis succesfully if i remove bullmq and use it somewhere else. Wondering what is the issue. Read all docs, 0 clue thanks to writers!

### How to reproduce.

Platform: Node 20 / 22 - Express  4.21
ENV is process.env for the project, it is replaced by a util. logger is pino but console.log is just fine. You can just change this lines and try to run it. 

Docker compose:

```
version: '3.7'
networks:
  common-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - common-network
      
  app:
    build:
      context: ./app  # Points to the directory with your Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - mongo
    networks:
      - common-network
    env_file: ./app/.env
```

redis uri in env, also shown above using containers bash:
```
REDIS_URI=redis://redis:6379/0
```

### Relevant log output

```shell
{"level":30,"time":1727641030469,"pid":18,"hostname":"1e30ac1f6e87", "env":"production","host":"redis","port":"6379","db":"0"}
{"level":30,"time":1727641030809,"pid":18,"hostname":"1e30ac1f6e87", "env":"production","msg":"Connected to Redis"}
MongoDB connected
...
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
